site_name: soerp3
site_description: Second Order Error Propagation for Python
site_url: https://eggzec.github.io/soerp3
repo_url: https://github.com/eggzec/soerp3
repo_name: eggzec/soerp3

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eggzec/soerp3
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/soerp3/

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Theory: theory.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - API Reference: api.md
  - References: references.md
